/*
 * This source file was generated by the Gradle 'init' task
 */
package org.APCSLowell;

public class GoogleBillboard {
    public boolean isPrime(long num){
    if(num<2)return false;
    else{
        for(int i =2;i<=Math.sqrt(num);i++){
            if(num%i==0)return false;}
        }return true;
    }
    public long firstPrimeNumberIn(String n) {
        for(int i=0;i<1000;i++){
            if(isPrime(Long.parseLong(n.substring(i,i+10)))==true){
                return Long.parseLong(n.substring(i,i+10)); 
            }
        }
        return -1;
    }
}
